services:
  api:
    build: .
    container_name: code_review_api
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - ollama
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build: .
    container_name: code_review_worker
    env_file:
      - .env
    depends_on:
      - redis
      - ollama
    command: celery -A app.celery_worker.celery worker --loglevel=INFO

  redis:
    image: redis:7
    container_name: code_review_redis
    ports:
      - "6379:6379"

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data: